### ISSUE TITLE
Error in printing of serial number and scaling

### ISSUE THREAD

**Issue by maehw** [PubInv/ventmon-ventilator-inline-test-monitor#10]
In SensirionFM3200/SFM3200/SFM3200.ino there's a function called requestSerialNumber:

```
  uint8_t a = Wire.read(); // first received byte stored here. The variable "uint16_t" can hold 2 bytes, this will be relevant later
  uint8_t b = Wire.read();
  uint8_t c = Wire.read(); // first received byte stored here. The variable "uint16_t" can hold 2 bytes, this will be relevant later
  uint8_t d = Wire.read(); 
  Serial.println(a,HEX);
  Serial.println(a,HEX);
  Serial.println(a,HEX);
  Serial.println(a,HEX);
```
As `a` is printed four times, this will not show the true serial number of the device.
I think you could base on my implementation under https://github.com/maehw/diy-beatmungsgeraet/tree/master/software/mass-airflow-sensor/controller-software - probably minor changes to support your Sensirion device, too.

Edit: I think there's another error in scaling:

```
 float scale = 120.0; // Scale factor for Air and N2 is 140.0, O2 is 142.8
```
The comment speaks of a value of around 140. Why do you use 120 in the code?

**Comment by RobertLRead** [comment]
This is a fantastic catch! Thank you very much --- I actually thought the Serial numbers were not working. Thank you, I have fixed it.

I use the scaling factor because the datasheet gives that for the SFM 3200 that I bought: https://www.mouser.com/datasheet/2/682/Sensirion_Mass_Flow_Meters_SFM3200-AW_Datasheet-1524538.pdf.

The comment came from code I copied from the internet. At the time I was not aware that Sensirion had that own library; I will now create a TODO item to use switch over to their library.  Your code is almost certainly far better, because the crc for the code I copied never worked.  So you have informed me of much; thank you!
