### ISSUE TITLE
What are capabilities ventmon offers beyond state of the art solutions?

### ISSUE THREAD

**Issue by synergiator** [PubInv/ventmon-ventilator-inline-test-monitor#5]
Looks like there are industrial solutions to profile performance of a human/respirator, what are benefits of building the new solution beyond an open design?

https://www.ingmarmed.com/product/respitrainer-advance/

**Comment by RobertLRead** [comment]
Since those products seem to cost at least $1500, an open design is inherently valuable (though mannequin-based models offer training capabilities we do not contemplate.)

But in particular, VentMon attempts allows inline MONITORING of a system. This means that an open-source ventilator that does not have its own monitoring capabilities (called out as mandatory in the British standard for Rapidly Manufactured Ventilator Systems [RMVS](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/876167/RMVS001_v3.1.pdf) could be met by building a basic ventilator and then using the VentMon as a monitoring solution.  In this since, it is a "modularization" of the total problem.
